{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyPLgBO+TlyjY7no59fWx1cI",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/Mehnaz-Bashir/Human-Activity-Recognition/blob/main/app/app.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 23,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "Foht3QqeSixy",
        "outputId": "ba3cb0e4-93cc-44ad-d10a-2a74bee2876d"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Overwriting app.py\n"
          ]
        }
      ],
      "source": [
        "%%writefile app.py\n",
        "import streamlit as st\n",
        "import pandas as pd\n",
        "import joblib\n",
        "import matplotlib.pyplot as plt\n",
        "\n",
        "# -----------------------------\n",
        "# Page Configuration\n",
        "# -----------------------------\n",
        "st.set_page_config(\n",
        "    page_title=\"Human Activity Recognition\",\n",
        "    page_icon=\"🏃\",\n",
        "    layout=\"wide\"\n",
        ")\n",
        "\n",
        "# -----------------------------\n",
        "# Load Model\n",
        "# -----------------------------\n",
        "import os\n",
        "\n",
        "BASE_DIR = os.path.dirname(os.path.abspath(__file__))\n",
        "\n",
        "st.write(\"Current Directory:\", BASE_DIR)\n",
        "st.write(\"Files here:\", os.listdir(BASE_DIR))\n",
        "st.write(\"Parent:\", os.listdir(os.path.join(BASE_DIR, \"..\")))\n",
        "st.write(\"Models:\", os.listdir(os.path.join(BASE_DIR, \"..\", \"models\")))\n",
        "\n",
        "MODEL_PATH = os.path.join(BASE_DIR, \"..\", \"models\", \"best_har_model.pkl\")\n",
        "FEATURE_PATH = os.path.join(BASE_DIR, \"..\", \"models\", \"feature_names.pkl\")\n",
        "\n",
        "st.write(\"Model exists:\", os.path.exists(MODEL_PATH))\n",
        "st.write(\"Feature exists:\", os.path.exists(FEATURE_PATH))\n",
        "\n",
        "model = joblib.load(MODEL_PATH)\n",
        "feature_names = joblib.load(FEATURE_PATH)\n",
        "\n",
        "activity_map = {\n",
        "    1: \"WALKING\",\n",
        "    2: \"WALKING_UPSTAIRS\",\n",
        "    3: \"WALKING_DOWNSTAIRS\",\n",
        "    4: \"SITTING\",\n",
        "    5: \"STANDING\",\n",
        "    6: \"LAYING\"\n",
        "}\n",
        "\n",
        "# -----------------------------\n",
        "# Sidebar\n",
        "# -----------------------------\n",
        "st.sidebar.title(\"🏃 HAR Dashboard\")\n",
        "\n",
        "st.sidebar.success(\"Model Loaded Successfully\")\n",
        "\n",
        "st.sidebar.metric(\n",
        "    label=\"Model Accuracy\",\n",
        "    value=\"98.59%\"\n",
        ")\n",
        "\n",
        "st.sidebar.markdown(\"---\")\n",
        "\n",
        "st.sidebar.write(\"### Activity Classes\")\n",
        "\n",
        "for value in activity_map.values():\n",
        "    st.sidebar.write(\"✅\", value)\n",
        "\n",
        "st.sidebar.markdown(\"---\")\n",
        "\n",
        "st.sidebar.info(\n",
        "\"\"\"\n",
        "Developer:\n",
        "Mehnaz Bashir\n",
        "\n",
        "MCA\n",
        "\n",
        "Lovely Professional University\n",
        "\"\"\"\n",
        ")\n",
        "\n",
        "# -----------------------------\n",
        "# Main Title\n",
        "# -----------------------------\n",
        "st.title(\"🏃 Human Activity Recognition\")\n",
        "\n",
        "st.write(\n",
        "\"\"\"\n",
        "Predict Human Activities using Smartphone Sensor Data.\n",
        "\"\"\"\n",
        ")\n",
        "\n",
        "st.markdown(\"---\")\n",
        "\n",
        "# -----------------------------\n",
        "# Upload CSV\n",
        "# -----------------------------\n",
        "uploaded_file = st.file_uploader(\n",
        "    \"📂 Upload Sensor CSV\",\n",
        "    type=\"csv\"\n",
        ")\n",
        "\n",
        "if uploaded_file is not None:\n",
        "\n",
        "    data = pd.read_csv(uploaded_file)\n",
        "\n",
        "    st.success(\"File Uploaded Successfully!\")\n",
        "\n",
        "    st.subheader(\"Dataset Preview\")\n",
        "\n",
        "    st.dataframe(data.head())\n",
        "\n",
        "    st.write(\"Rows :\", data.shape[0])\n",
        "    st.write(\"Columns :\", data.shape[1])\n",
        "\n",
        "    # -----------------------------\n",
        "    # Predict Button\n",
        "    # -----------------------------\n",
        "\n",
        "    if st.button(\"🚀 Predict Activities\"):\n",
        "\n",
        "        data = data[feature_names]\n",
        "\n",
        "        predictions = model.predict(data)\n",
        "\n",
        "        predicted_labels = [\n",
        "            activity_map[p]\n",
        "            for p in predictions\n",
        "        ]\n",
        "\n",
        "        data[\"Predicted Activity\"] = predicted_labels\n",
        "\n",
        "        st.success(\"Prediction Completed!\")\n",
        "\n",
        "        # -----------------------------\n",
        "        # Prediction Results\n",
        "        # -----------------------------\n",
        "\n",
        "        st.subheader(\"Prediction Results\")\n",
        "\n",
        "        st.dataframe(data)\n",
        "\n",
        "        # -----------------------------\n",
        "        # Summary\n",
        "        # -----------------------------\n",
        "\n",
        "        st.subheader(\"Prediction Summary\")\n",
        "\n",
        "        summary = data[\"Predicted Activity\"].value_counts()\n",
        "\n",
        "        st.dataframe(summary)\n",
        "\n",
        "        # -----------------------------\n",
        "        # Charts\n",
        "        # -----------------------------\n",
        "\n",
        "        col1, col2 = st.columns(2)\n",
        "\n",
        "        with col1:\n",
        "\n",
        "            fig, ax = plt.subplots(figsize=(6,4))\n",
        "\n",
        "            summary.plot(\n",
        "                kind=\"bar\",\n",
        "                ax=ax\n",
        "            )\n",
        "\n",
        "            ax.set_title(\"Activity Distribution\")\n",
        "\n",
        "            ax.set_ylabel(\"Count\")\n",
        "\n",
        "            st.pyplot(fig)\n",
        "\n",
        "        with col2:\n",
        "\n",
        "            fig2, ax2 = plt.subplots(figsize=(6,6))\n",
        "\n",
        "            summary.plot(\n",
        "                kind=\"pie\",\n",
        "                autopct=\"%1.1f%%\",\n",
        "                ax=ax2\n",
        "            )\n",
        "\n",
        "            ax2.set_ylabel(\"\")\n",
        "\n",
        "            ax2.set_title(\"Activity Percentage\")\n",
        "\n",
        "            st.pyplot(fig2)\n",
        "\n",
        "        # -----------------------------\n",
        "        # Download\n",
        "        # -----------------------------\n",
        "\n",
        "        csv = data.to_csv(index=False).encode(\"utf-8\")\n",
        "\n",
        "        st.download_button(\n",
        "            label=\"⬇ Download Predictions\",\n",
        "            data=csv,\n",
        "            file_name=\"predictions.csv\",\n",
        "            mime=\"text/csv\"\n",
        "        )"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import os\n",
        "os.listdir()"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "rDZ6awweS2fO",
        "outputId": "a1f32a52-67fe-4b89-8fff-64f9d4875ca5"
      },
      "execution_count": 17,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "['.config',\n",
              " 'logs.txt',\n",
              " 'app.py',\n",
              " 'feature_names.pkl',\n",
              " 'best_har_model.pkl',\n",
              " 'sample_data']"
            ]
          },
          "metadata": {},
          "execution_count": 17
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "!pip install streamlit pyngrok"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "6ePDX5X6XRyC",
        "outputId": "b4633766-370f-4c77-de91-74b76eac9c06"
      },
      "execution_count": 5,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Collecting streamlit\n",
            "  Downloading streamlit-1.59.2-py3-none-any.whl.metadata (9.6 kB)\n",
            "Collecting pyngrok\n",
            "  Downloading pyngrok-8.1.2-py3-none-any.whl.metadata (8.6 kB)\n",
            "Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.5.0)\n",
            "Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (1.9.0)\n",
            "Requirement already satisfied: cachetools<8,>=5.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.2.6)\n",
            "Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (8.4.2)\n",
            "Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.12/dist-packages (from streamlit) (3.1.51)\n",
            "Requirement already satisfied: numpy<3,>=1.23 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.0.2)\n",
            "Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (26.2)\n",
            "Requirement already satisfied: pandas<4,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.2.2)\n",
            "Requirement already satisfied: pillow<13,>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (11.3.0)\n",
            "Collecting pydeck<1,>=0.8.0b4 (from streamlit)\n",
            "  Downloading pydeck-0.9.3-py2.py3-none-any.whl.metadata (4.2 kB)\n",
            "Requirement already satisfied: protobuf<8,>=3.20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.29.6)\n",
            "Requirement already satisfied: pyarrow<25,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (18.1.0)\n",
            "Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.32.4)\n",
            "Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (9.1.4)\n",
            "Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.10.2)\n",
            "Requirement already satisfied: typing-extensions<5,>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.16.0)\n",
            "Requirement already satisfied: starlette>=0.40.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (1.3.1)\n",
            "Requirement already satisfied: uvicorn>=0.30.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.51.0)\n",
            "Requirement already satisfied: httptools>=0.6.3 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.8.0)\n",
            "Requirement already satisfied: anyio>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.14.2)\n",
            "Requirement already satisfied: python-multipart>=0.0.10 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.0.32)\n",
            "Requirement already satisfied: websockets>=12.0.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (15.0.1)\n",
            "Requirement already satisfied: itsdangerous>=2.1.2 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.2.0)\n",
            "Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.0.0)\n",
            "Requirement already satisfied: PyYAML>=5.1 in /usr/local/lib/python3.12/dist-packages (from pyngrok) (6.0.3)\n",
            "Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)\n",
            "Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.26.0)\n",
            "Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.24.0)\n",
            "Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio>=4.0.0->streamlit) (3.18)\n",
            "Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)\n",
            "Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2.9.0.post0)\n",
            "Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2025.2)\n",
            "Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2026.3)\n",
            "Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.4.9)\n",
            "Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2.5.0)\n",
            "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2026.6.17)\n",
            "Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.12/dist-packages (from uvicorn>=0.30.0->streamlit) (0.16.0)\n",
            "Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.3)\n",
            "Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.3)\n",
            "Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (26.1.0)\n",
            "Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.9.1)\n",
            "Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.37.0)\n",
            "Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2026.6.3)\n",
            "Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<4,>=1.4.0->streamlit) (1.17.0)\n",
            "Downloading streamlit-1.59.2-py3-none-any.whl (10.3 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m10.3/10.3 MB\u001b[0m \u001b[31m74.5 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading pyngrok-8.1.2-py3-none-any.whl (25 kB)\n",
            "Downloading pydeck-0.9.3-py2.py3-none-any.whl (11.4 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m11.4/11.4 MB\u001b[0m \u001b[31m103.5 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hInstalling collected packages: pyngrok, pydeck, streamlit\n",
            "Successfully installed pydeck-0.9.3 pyngrok-8.1.2 streamlit-1.59.2\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "!streamlit run app.py &>/content/logs.txt &"
      ],
      "metadata": {
        "id": "fDjKVEW7XU0g"
      },
      "execution_count": 6,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "from pyngrok import ngrok\n",
        "\n",
        "# Replace 'YOUR_AUTHTOKEN' with your actual ngrok authentication token\n",
        "# You can find your authtoken at https://dashboard.ngrok.com/get-started/your-authtoken\n",
        "ngrok.set_auth_token('3DtXscKi9gAmZJuk3jee3Zp0xQz_4fDHGfxqcqSnpHvupkQoJ')\n",
        "\n",
        "public_url = ngrok.connect(8501)\n",
        "print(public_url)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "NKcYTS7OXXlO",
        "outputId": "534b06ff-58fd-4587-865b-443d360e546c"
      },
      "execution_count": 9,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "NgrokTunnel: \"https://student-resupply-directly.ngrok-free.dev\" -> \"http://localhost:8501\"\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "bb59fc82",
        "outputId": "a203e355-771a-4de2-c6e8-4aee51508307"
      },
      "source": [
        "with open('app.py', 'r') as f:\n",
        "    app_code = f.read()\n",
        "print(app_code)"
      ],
      "execution_count": 11,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "import streamlit as st\n",
            "import pandas as pd\n",
            "import joblib\n",
            "import matplotlib.pyplot as plt\n",
            "\n",
            "# -----------------------------\n",
            "# Page Configuration\n",
            "# -----------------------------\n",
            "st.set_page_config(\n",
            "    page_title=\"Human Activity Recognition\",\n",
            "    page_icon=\"🏃\",\n",
            "    layout=\"wide\"\n",
            ")\n",
            "\n",
            "# -----------------------------\n",
            "# Load Model\n",
            "# -----------------------------\n",
            "model = joblib.load(\"../models/best_har_model.pkl\")\n",
            "feature_names = joblib.load(\"../models/feature_names.pkl\")\n",
            "\n",
            "activity_map = {\n",
            "    1: \"WALKING\",\n",
            "    2: \"WALKING_UPSTAIRS\",\n",
            "    3: \"WALKING_DOWNSTAIRS\",\n",
            "    4: \"SITTING\",\n",
            "    5: \"STANDING\",\n",
            "    6: \"LAYING\"\n",
            "}\n",
            "\n",
            "# -----------------------------\n",
            "# Sidebar\n",
            "# -----------------------------\n",
            "st.sidebar.title(\"🏃 HAR Dashboard\")\n",
            "\n",
            "st.sidebar.success(\"Model Loaded Successfully\")\n",
            "\n",
            "st.sidebar.metric(\n",
            "    label=\"Model Accuracy\",\n",
            "    value=\"98.59%\"\n",
            ")\n",
            "\n",
            "st.sidebar.markdown(\"---\")\n",
            "\n",
            "st.sidebar.write(\"### Activity Classes\")\n",
            "\n",
            "for value in activity_map.values():\n",
            "    st.sidebar.write(\"✅\", value)\n",
            "\n",
            "st.sidebar.markdown(\"---\")\n",
            "\n",
            "st.sidebar.info(\n",
            "\"\"\"\n",
            "Developer:\n",
            "Mehnaz Bashir\n",
            "\n",
            "MCA\n",
            "\n",
            "Lovely Professional University\n",
            "\"\"\"\n",
            ")\n",
            "\n",
            "# -----------------------------\n",
            "# Main Title\n",
            "# -----------------------------\n",
            "st.title(\"🏃 Human Activity Recognition\")\n",
            "\n",
            "st.write(\n",
            "\"\"\"\n",
            "Predict Human Activities using Smartphone Sensor Data.\n",
            "\"\"\"\n",
            ")\n",
            "\n",
            "st.markdown(\"---\")\n",
            "\n",
            "# -----------------------------\n",
            "# Upload CSV\n",
            "# -----------------------------\n",
            "uploaded_file = st.file_uploader(\n",
            "    \"📂 Upload Sensor CSV\",\n",
            "    type=\"csv\"\n",
            ")\n",
            "\n",
            "if uploaded_file is not None:\n",
            "\n",
            "    data = pd.read_csv(uploaded_file)\n",
            "\n",
            "    st.success(\"File Uploaded Successfully!\")\n",
            "\n",
            "    st.subheader(\"Dataset Preview\")\n",
            "\n",
            "    st.dataframe(data.head())\n",
            "\n",
            "    st.write(\"Rows :\", data.shape[0])\n",
            "    st.write(\"Columns :\", data.shape[1])\n",
            "\n",
            "    # -----------------------------\n",
            "    # Predict Button\n",
            "    # -----------------------------\n",
            "\n",
            "    if st.button(\"🚀 Predict Activities\"):\n",
            "\n",
            "        data = data[feature_names]\n",
            "\n",
            "        predictions = model.predict(data)\n",
            "\n",
            "        predicted_labels = [\n",
            "            activity_map[p]\n",
            "            for p in predictions\n",
            "        ]\n",
            "\n",
            "        data[\"Predicted Activity\"] = predicted_labels\n",
            "\n",
            "        st.success(\"Prediction Completed!\")\n",
            "\n",
            "        # -----------------------------\n",
            "        # Prediction Results\n",
            "        # -----------------------------\n",
            "\n",
            "        st.subheader(\"Prediction Results\")\n",
            "\n",
            "        st.dataframe(data)\n",
            "\n",
            "        # -----------------------------\n",
            "        # Summary\n",
            "        # -----------------------------\n",
            "\n",
            "        st.subheader(\"Prediction Summary\")\n",
            "\n",
            "        summary = data[\"Predicted Activity\"].value_counts()\n",
            "\n",
            "        st.dataframe(summary)\n",
            "\n",
            "        # -----------------------------\n",
            "        # Charts\n",
            "        # -----------------------------\n",
            "\n",
            "        col1, col2 = st.columns(2)\n",
            "\n",
            "        with col1:\n",
            "\n",
            "            fig, ax = plt.subplots(figsize=(6,4))\n",
            "\n",
            "            summary.plot(\n",
            "                kind=\"bar\",\n",
            "                ax=ax\n",
            "            )\n",
            "\n",
            "            ax.set_title(\"Activity Distribution\")\n",
            "\n",
            "            ax.set_ylabel(\"Count\")\n",
            "\n",
            "            st.pyplot(fig)\n",
            "\n",
            "        with col2:\n",
            "\n",
            "            fig2, ax2 = plt.subplots(figsize=(6,6))\n",
            "\n",
            "            summary.plot(\n",
            "                kind=\"pie\",\n",
            "                autopct=\"%1.1f%%\",\n",
            "                ax=ax2\n",
            "            )\n",
            "\n",
            "            ax2.set_ylabel(\"\")\n",
            "\n",
            "            ax2.set_title(\"Activity Percentage\")\n",
            "\n",
            "            st.pyplot(fig2)\n",
            "\n",
            "        # -----------------------------\n",
            "        # Download\n",
            "        # -----------------------------\n",
            "\n",
            "        csv = data.to_csv(index=False).encode(\"utf-8\")\n",
            "\n",
            "        st.download_button(\n",
            "            label=\"⬇ Download Predictions\",\n",
            "            data=csv,\n",
            "            file_name=\"predictions.csv\",\n",
            "            mime=\"text/csv\"\n",
            "        )\n",
            "\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "22ad69ff",
        "outputId": "4b401e94-35a5-4cda-bfcb-e83bfdd0f02a"
      },
      "source": [
        "with open('/content/logs.txt', 'r') as f:\n",
        "    logs = f.read()\n",
        "print(logs)"
      ],
      "execution_count": 10,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\n",
            "Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.\n",
            "\n",
            "2026-07-21 20:28:20.092 Uvicorn server started on :::8501\n",
            "\n",
            "  You can now view your Streamlit app in your browser.\n",
            "\n",
            "  Local URL: http://localhost:8501\n",
            "  Network URL: http://172.28.0.12:8501\n",
            "  External URL: http://136.65.173.195:8501\n",
            "\n",
            "\n"
          ]
        }
      ]
    }
  ]
}